# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'date'

BusinessAttribute.destroy_all
AttributeItem.destroy_all
Review.destroy_all
User.destroy_all
ServiceItem.destroy_all
Service.destroy_all
BusinessOperationHour.destroy_all
OperationHour.destroy_all
Business.destroy_all

# Seed AttributeItems
attr1 = AttributeItem.create!(attribute_type: "Cuisine", name: "Italian")
attr2 = AttributeItem.create!(attribute_type: "Cuisine", name: "Lebanse")
attr3 = AttributeItem.create!(attribute_type: "Cuisine", name: "Brunch")
attr4 = AttributeItem.create!(attribute_type: "Cuisine", name: "Ramen")
attr5 = AttributeItem.create!(attribute_type: "Cuisine", name: "Sushi")
attr6 = AttributeItem.create!(attribute_type: "Cuisine", name: "Pizza")
attr7 = AttributeItem.create!(attribute_type: "Cuisine", name: "French")
attr8 = AttributeItem.create!(attribute_type: "Cuisine", name: "American")
attr9 = AttributeItem.create!(attribute_type: "Cuisine", name: "Chinese")
attr10 = AttributeItem.create!(attribute_type: "Cuisine", name: "Burgers")
attr11 = AttributeItem.create!(attribute_type: "Cuisine", name: "Atlantian")
attr12 = AttributeItem.create!(attribute_type: "Cuisine", name: "Indian")
attr13 = AttributeItem.create!(attribute_type: "Neighborhood", name: "Little Whinging")
attr14 = AttributeItem.create!(attribute_type: "Neighborhood", name: "Hogsmeade")
attr15 = AttributeItem.create!(attribute_type: "Neighborhood", name: "Diagon Alley")
attr16 = AttributeItem.create!(attribute_type: "Neighborhood", name: "Knockturn Alley")
attr17 = AttributeItem.create!(attribute_type: "Neighborhood", name: "Godric's Hollow")
attr18 = AttributeItem.create!(attribute_type: "Business Type", name: "Wand Repair")
attr19 = AttributeItem.create!(attribute_type: "Business Type", name: "Potion Supplies")
attr20 = AttributeItem.create!(attribute_type: "Business Type", name: "Curse Removal")
attr21 = AttributeItem.create!(attribute_type: "Business Type", name: "Restaurant")
attr22 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Takeout")
attr23 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Reservations")
attr24 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Waiter Service")
attr25 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Outdoor Seating")
attr26 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Good for Groups")
attr27 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Happy Hour")
attr28 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Delivery")
attr29 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Full Bar")
attr30 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Wi-Fi")
attr31 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Good for Kids")
attr32 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Pets Allowed")
attr33 = AttributeItem.create!(attribute_type: "Misc Attribute", name: "Wheelchair Accessible")

# Seed Business
business1 = Business.create!(name: "Filona's Fanciful Foods", address:"address1", lat: -37.972125, lng: 175.682933)
business2 = Business.create!(name: "Randery's Rambunctious Raclettery", address:"address2", lat: -37.872125, lng: 175.782933)
business3 = Business.create!(name: "Mutton Man", address:"address3", lat: -37.872125, lng: 175.582933)
business4 = Business.create!(name: "The Black Tea House", address:"address4", lat: -37.872125, lng: 175.582933)
business5 = Business.create!(name: "Windburg's Wonderful Wands", address:"address5", lat: -37.872125, lng: 175.582933)
business6 = Business.create!(name: "Better Brooms", address:"address6", lat: -37.872125, lng: 175.582933)
business7 = Business.create!(name: "Curiously Conspicuous Cocktails", address:"address7", lat: -37.872125, lng: 175.582933)
business8 = Business.create!(name: "Razzling Racers", address:"address8", lat: -37.872125, lng: 175.582933)
business9 = Business.create!(name: "Hibbidy Dippity Bad", address:"address9", lat: -37.872125, lng: 175.582933)
business10 = Business.create!(name: "Plenty'O'Potions", address:"address10", lat: -37.872125, lng: 175.582933)

# Seed OperationHour
sunOpen = OperationHour.create!(day: 0, biz_time: 10)
sunClose = OperationHour.create!(day: 0, biz_time: 22)
monOpen = OperationHour.create!(day: 1, biz_time: 10)
monClose = OperationHour.create!(day: 1, biz_time: 22)
tuesOpen = OperationHour.create!(day: 2, biz_time: 10)
tuesClose = OperationHour.create!(day: 2, biz_time: 22)
wedOpen = OperationHour.create!(day: 3, biz_time: 10)
wedClose = OperationHour.create!(day: 3, biz_time: 22)
thursOpen = OperationHour.create!(day: 4, biz_time: 10)
thursClose = OperationHour.create!(day: 4, biz_time: 22)
friOpen = OperationHour.create!(day: 5, biz_time: 10)
friClose = OperationHour.create!(day: 5, biz_time: 23)
satOpen = OperationHour.create!(day: 6, biz_time: 10.5)
satClose = OperationHour.create!(day: 6, biz_time: 23)

# Seed Service
service1 = Service.create!(business_id: business1.id, service_type: "Brunch Menu", name: "Brunch Menu")
service2 = Service.create!(business_id: business2.id, service_type: "Dinner Menu", name: "Dinner Menu")
service3 = Service.create!(business_id: business3.id, service_type: "Cocktails", name: "Happy Hour")

# Seed ServiceItem
serviceItem1 = ServiceItem.create!(service_id: service1.id, name: "Boiled Newt", price: 1.5)
serviceItem2 = ServiceItem.create!(service_id: service1.id, name: "Rabbit Feet", price: 2.5)
serviceItem3 = ServiceItem.create!(service_id: service2.id, name: "Butterbeer", price: 5)
serviceItem4 = ServiceItem.create!(service_id: service2.id, name: "Floating Chocolate Pie", price: 10.5)
serviceItem5 = ServiceItem.create!(service_id: service3.id, name: "Mutton", price: 12)
serviceItem6 = ServiceItem.create!(service_id: service3.id, name: "Frog Leg Tacos", price: 7)

# Seed User
demoUser =  User.create!(email: "demo@mail.com", f_name: "Demo", l_name: "User", password: "password", zip_code:11111)
ron = User.create!(email: "rweasley@magic.com", f_name: "Ron", l_name: "Weasley", password: "password", zip_code:11111)
harry = User.create!(email: "BoyWhoLived@hogwarts.edu", f_name: "Harry", l_name: "Potter", password: "password", zip_code:11111)
mcgonagall = User.create!(email: "mcgonagall@hogwarts.edu", f_name: "Minerva", l_name: "McGonagall", password: "password", zip_code:11111)
dumbledore = User.create!(email: "ddore@pensive.gov", f_name: "Albus", l_name: "Dumbledore", password: "password", zip_code:11111)
hermoine= User.create!(email: "hermoine@newZealandTourism.gov", f_name: "Hermione", l_name: "Granger", password: "password", zip_code:11111)
darkLord = User.create!(email: "needanose@wheremynose.com", f_name: "Tom", l_name: "Riddle", password: "password", zip_code:11111)
hagrid = User.create!(email: "hagrid@forbiddenforest.com", f_name: "Rebeus", l_name: "Riddle", password: "password", zip_code:11111)
snape = User.create!(email: "misunderstood@tragic.com", f_name: "Severus", l_name: "Snape", password: "password", zip_code:11111)
malfoy = User.create!(email: "imtelling@myfather.com", f_name: "Drako", l_name: "Malfoy", password: "password", zip_code:11111)
sirius = User.create!(email: "woof@shaggy.com", f_name: "Sirius", l_name: "Black", password: "password", zip_code:11111)

# Seed Review
review1 = Review.create!(user_id: demoUser.id, business_id: business1.id, rating: 5, body: "Loved the chocolate frogs!")
review2 = Review.create!(user_id: harry.id, business_id: business1.id, rating: 4, body: "My dessert literally danced off the plate. I had to go chasing after it!")
review3 = Review.create!(user_id: dumbledore.id, business_id: business1.id, rating: 5, body: "The flakey pastries were utterly delightful")
review4 = Review.create!(user_id: ron.id, business_id: business1.id, rating: 5, body: "*Burp* Delicious~")
review5 = Review.create!(user_id: hermoine.id, business_id: business1.id, rating: 4, body: "The food was very good, but I was too busy studying to really pay attention.")
review6 = Review.create!(user_id: demoUser.id, business_id: business2.id, rating: 5, body: "The cheesey potatoes were my favorite.")
review7 = Review.create!(user_id: snape.id, business_id: business2.id, rating: 2, body: "The room was far too brightly lit and the patrons would stop their shrill laughter.")
review8 = Review.create!(user_id: sirius.id, business_id: business2.id, rating: 5, body: "Sometimes when I transfigure to a dog they feed me scraps in the back.")
review9 = Review.create!(user_id: darkLord.id, business_id: business2.id, rating: 1, body: "*HISS!!*")
review10 = Review.create!(user_id: malfoy.id, business_id: business2.id, rating: 2, body: "My father gave us the best seats in the restaurant. But this food is for peasants.")
review11 = Review.create!(user_id: demoUser.id, business_id: business3.id, rating: 4, body: "The only item the serve is mutton. But it was the best mutton I eve had.")
review12 = Review.create!(user_id: hermoine.id, business_id: business3.id, rating: 5, body: "I think I like mutton now.")
review13 = Review.create!(user_id: sirius.id, business_id: business3.id, rating: 5, body: "James and Lily would have loved this")
review14 = Review.create!(user_id: ron.id, business_id: business3.id, rating: 5, body: "All I have to say is mmm-mmm-mutton!")
review15 = Review.create!(user_id: harry.id, business_id: business3.id, rating: 5, body: "I thinkt his is the type of meal my mum would have made.")
review16 = Review.create!(user_id: demoUser.id, business_id: business4.id, rating: 2, body: "I had to be careful, some of these teas were cursed and others were poisonous.")
review17 = Review.create!(user_id: dumbledore.id, business_id: business4.id, rating: 3, body: "Such a perplexing visit with an odd assortment of teas")
review18 = Review.create!(user_id: darkLord.id, business_id: business4.id, rating: 1, body: "*HISS!!!*")
review19 = Review.create!(user_id: sirius.id, business_id: business4.id, rating: 1, body: "I almost died!")
review20 = Review.create!(user_id: hagrid.id, business_id: business4.id, rating: 5, body: "I loved it! Some of the teas made me feel a little sloshed, but I slept it off fine.")
review21 = Review.create!(user_id: demoUser.id, business_id: business5.id, rating: 4, body: "I like my wand, but it was a bit pricey.")
review22 = Review.create!(user_id: malfoy.id, business_id: business5.id, rating: 3, body: "The wand was amazing, but the owner is a complete buffoon, oggling over Harry Potter.")
review23 = Review.create!(user_id: harry.id, business_id: business5.id, rating: 4, body: "I like this place, but all the attention the owner gives me is a bit much.")
review24 = Review.create!(user_id: ron.id, business_id: business5.id, rating: 5, body: "I got free stuff since I went with Harry!")
review25 = Review.create!(user_id: hermoine.id, business_id: business5.id, rating: 4, body: "A very friendly shop owner with some nice but expensive wands.")
review26 = Review.create!(user_id: demoUser.id, business_id: business6.id, rating: 5, body: "I can't wait to use my new broom to tryout for the quidditch team!")
review27 = Review.create!(user_id: ron.id, business_id: business6.id, rating: 5, body: "Luckily they had some used brooms I was able to find")
review28 = Review.create!(user_id: malfoy.id, business_id: business6.id, rating: 4, body: "They have the new Nimbus 10,000! Wait until Potter sees this")
review29 = Review.create!(user_id: darkLord.id, business_id: business6.id, rating: 1, body: "*HISS!!!!*")
review30 = Review.create!(user_id: harry.id, business_id: business6.id, rating: 2, body: "They were able to repair the Nimbus 5000 that Sirius gave me. Works like new!")
review31 = Review.create!(user_id: demoUser.id, business_id: business7.id, rating: 4, body: "Love the ambiance!")
review32 = Review.create!(user_id: snape.id, business_id: business7.id, rating: 4, body: "I was forced to come on a holiday party. Far too much cheer in the air")
review33 = Review.create!(user_id: dumbledore.id, business_id: business7.id, rating: 4, body: "Such a wonderful time! I even learned a new charm for bedazzling my spectacles")
review34 = Review.create!(user_id: hagrid.id, business_id: business7.id, rating: 4, body: "I was able to order le by the barrel! It was a lovely party")
review35 = Review.create!(user_id: mcgonagall.id, business_id: business7.id, rating: 4, body: "I dare say, the cocktails are divine")
review36 = Review.create!(user_id: demoUser.id, business_id: business8.id, rating: 5, body: "I was able to sell my old broom for a good price!")
review37 = Review.create!(user_id: harry.id, business_id: business8.id, rating: 5, body: "We got the whole Gryfindor team new brooms!")
review38 = Review.create!(user_id: ron.id, business_id: business8.id, rating: 4, body: "I GOT A NEW BROOM!")
review39 = Review.create!(user_id: hermoine.id, business_id: business8.id, rating: 5, body: "The shop owner was a delight to work with")
review40 = Review.create!(user_id: mcgonagall.id, business_id: business8.id, rating: 4, body: "Wait till the children see what it really means to ride a broom")
review41 = Review.create!(user_id: demoUser.id, business_id: business9.id, rating: 5, body: "I went there last week and was able to turn my arm back to normal! Great service!")
review42 = Review.create!(user_id: harry.id, business_id: business9.id, rating: 5, body: "I was able to get a curse removed with Voldemort placed on me! Can't believe how skilled they are here")
review43 = Review.create!(user_id: darkLord.id, business_id: business9.id, rating: 1, body: "*HISS!!!!!*")
review44 = Review.create!(user_id: dumbledore.id, business_id: business9.id, rating: 5, body: "I'm quite impressed with their quality of work")
review45 = Review.create!(user_id: snape.id, business_id: business9.id, rating: 5, body: "The owner and I get along well. I can tolerate this place, to an extent.")
review46 = Review.create!(user_id: demoUser.id, business_id: business10.id, rating: 1, body: "Turns out this place is kinda evil. Like, actually evil.")
review47 = Review.create!(user_id: mcgonagall.id, business_id: business10.id, rating: 1, body: "This place is run by Death Eaters!")
review48 = Review.create!(user_id: dumbledore.id, business_id: business10.id, rating: 1, body: "The pixie soup was quite bland. Also, the owners of this location happen to be Death Eaters.")
review49 = Review.create!(user_id: sirius.id, business_id: business10.id, rating: 1, body: "How dare Death Eaters open a shop, flaunting their serpent skulls! Meanwhile, I must hide in the shadows, not even able to see poor harry.")
review50 = Review.create!(user_id: hagrid.id, business_id: business10.id, rating: 1, body: "Awful rude people working here.")

# Seed BusinessAttributes: Joins table for Bussiness and AttributeItem
AttrListB1A1 = BusinessAttribute.create!(business_id: business1.id, attribute_item_id: attr1.id)
AttrListB1A13 = BusinessAttribute.create!(business_id: business1.id, attribute_item_id: attr13.id)
AttrListB1A21 = BusinessAttribute.create!(business_id: business1.id, attribute_item_id: attr21.id)
AttrListB1A30 = BusinessAttribute.create!(business_id: business1.id, attribute_item_id: attr30.id)
AttrListB1A35 = BusinessAttribute.create!(business_id: business1.id, attribute_item_id: attr25.id)
AttrListB1A33 = BusinessAttribute.create!(business_id: business1.id, attribute_item_id: attr33.id)

AttrListB2A2 = BusinessAttribute.create!(business_id: business2.id, attribute_item_id: attr2.id)
AttrListB2A3 = BusinessAttribute.create!(business_id: business2.id, attribute_item_id: attr3.id)
AttrListB2A16 = BusinessAttribute.create!(business_id: business2.id, attribute_item_id: attr16.id)
AttrListB2A21 = BusinessAttribute.create!(business_id: business2.id, attribute_item_id: attr21.id)
AttrListB2A24 = BusinessAttribute.create!(business_id: business2.id, attribute_item_id: attr24.id)
AttrListB2A32 = BusinessAttribute.create!(business_id: business2.id, attribute_item_id: attr32.id)
AttrListB2A33 = BusinessAttribute.create!(business_id: business2.id, attribute_item_id: attr33.id)

AttrListB3A8 = BusinessAttribute.create!(business_id: business3.id, attribute_item_id: attr8.id)
AttrListB3A10 = BusinessAttribute.create!(business_id: business3.id, attribute_item_id: attr10.id)
AttrListB3A17 = BusinessAttribute.create!(business_id: business3.id, attribute_item_id: attr17.id)
AttrListB3A21 = BusinessAttribute.create!(business_id: business3.id, attribute_item_id: attr21.id)
AttrListB3A27 = BusinessAttribute.create!(business_id: business3.id, attribute_item_id: attr27.id)
AttrListB3A29 = BusinessAttribute.create!(business_id: business3.id, attribute_item_id: attr29.id)
AttrListB3A33 = BusinessAttribute.create!(business_id: business3.id, attribute_item_id: attr33.id)

AttrListB3A8 = BusinessAttribute.create!(business_id: business4.id, attribute_item_id: attr8.id)
AttrListB3A10 = BusinessAttribute.create!(business_id: business4.id, attribute_item_id: attr10.id)
AttrListB3A17 = BusinessAttribute.create!(business_id: business4.id, attribute_item_id: attr17.id)
AttrListB3A21 = BusinessAttribute.create!(business_id: business4.id, attribute_item_id: attr21.id)
AttrListB3A27 = BusinessAttribute.create!(business_id: business4.id, attribute_item_id: attr27.id)
AttrListB3A29 = BusinessAttribute.create!(business_id: business4.id, attribute_item_id: attr29.id)
AttrListB3A33 = BusinessAttribute.create!(business_id: business4.id, attribute_item_id: attr33.id)

AttrListB3A8 = BusinessAttribute.create!(business_id: business5.id, attribute_item_id: attr8.id)
AttrListB3A10 = BusinessAttribute.create!(business_id: business5.id, attribute_item_id: attr10.id)
AttrListB3A17 = BusinessAttribute.create!(business_id: business5.id, attribute_item_id: attr17.id)
AttrListB3A21 = BusinessAttribute.create!(business_id: business5.id, attribute_item_id: attr21.id)
AttrListB3A27 = BusinessAttribute.create!(business_id: business5.id, attribute_item_id: attr27.id)
AttrListB3A29 = BusinessAttribute.create!(business_id: business5.id, attribute_item_id: attr29.id)
AttrListB3A33 = BusinessAttribute.create!(business_id: business5.id, attribute_item_id: attr33.id)

AttrListB3A8 = BusinessAttribute.create!(business_id: business6.id, attribute_item_id: attr8.id)
AttrListB3A10 = BusinessAttribute.create!(business_id: business6.id, attribute_item_id: attr10.id)
AttrListB3A17 = BusinessAttribute.create!(business_id: business6.id, attribute_item_id: attr17.id)
AttrListB3A21 = BusinessAttribute.create!(business_id: business6.id, attribute_item_id: attr21.id)
AttrListB3A27 = BusinessAttribute.create!(business_id: business6.id, attribute_item_id: attr27.id)
AttrListB3A29 = BusinessAttribute.create!(business_id: business6.id, attribute_item_id: attr29.id)
AttrListB3A33 = BusinessAttribute.create!(business_id: business6.id, attribute_item_id: attr33.id)

AttrListB3A8 = BusinessAttribute.create!(business_id: business7.id, attribute_item_id: attr8.id)
AttrListB3A10 = BusinessAttribute.create!(business_id: business7.id, attribute_item_id: attr10.id)
AttrListB3A17 = BusinessAttribute.create!(business_id: business7.id, attribute_item_id: attr17.id)
AttrListB3A21 = BusinessAttribute.create!(business_id: business7.id, attribute_item_id: attr21.id)
AttrListB3A27 = BusinessAttribute.create!(business_id: business7.id, attribute_item_id: attr27.id)
AttrListB3A29 = BusinessAttribute.create!(business_id: business7.id, attribute_item_id: attr29.id)
AttrListB3A33 = BusinessAttribute.create!(business_id: business7.id, attribute_item_id: attr33.id)

AttrListB3A8 = BusinessAttribute.create!(business_id: business8.id, attribute_item_id: attr8.id)
AttrListB3A10 = BusinessAttribute.create!(business_id: business8.id, attribute_item_id: attr10.id)
AttrListB3A17 = BusinessAttribute.create!(business_id: business8.id, attribute_item_id: attr17.id)
AttrListB3A21 = BusinessAttribute.create!(business_id: business8.id, attribute_item_id: attr21.id)
AttrListB3A27 = BusinessAttribute.create!(business_id: business8.id, attribute_item_id: attr27.id)
AttrListB3A29 = BusinessAttribute.create!(business_id: business8.id, attribute_item_id: attr29.id)
AttrListB3A33 = BusinessAttribute.create!(business_id: business8.id, attribute_item_id: attr33.id)

AttrListB3A8 = BusinessAttribute.create!(business_id: business9.id, attribute_item_id: attr8.id)
AttrListB3A10 = BusinessAttribute.create!(business_id: business9.id, attribute_item_id: attr10.id)
AttrListB3A17 = BusinessAttribute.create!(business_id: business9.id, attribute_item_id: attr17.id)
AttrListB3A21 = BusinessAttribute.create!(business_id: business9.id, attribute_item_id: attr21.id)
AttrListB3A27 = BusinessAttribute.create!(business_id: business9.id, attribute_item_id: attr27.id)
AttrListB3A29 = BusinessAttribute.create!(business_id: business9.id, attribute_item_id: attr29.id)
AttrListB3A33 = BusinessAttribute.create!(business_id: business9.id, attribute_item_id: attr33.id)

AttrListB3A8 = BusinessAttribute.create!(business_id: business10.id, attribute_item_id: attr8.id)
AttrListB3A10 = BusinessAttribute.create!(business_id: business10.id, attribute_item_id: attr10.id)
AttrListB3A17 = BusinessAttribute.create!(business_id: business10.id, attribute_item_id: attr17.id)
AttrListB3A21 = BusinessAttribute.create!(business_id: business10.id, attribute_item_id: attr21.id)
AttrListB3A27 = BusinessAttribute.create!(business_id: business10.id, attribute_item_id: attr27.id)
AttrListB3A29 = BusinessAttribute.create!(business_id: business10.id, attribute_item_id: attr29.id)
AttrListB3A33 = BusinessAttribute.create!(business_id: business10.id, attribute_item_id: attr33.id)

# Seed BusinessOperationHours: Joins table for businesses and hours_of_operation
sbhB1H1 = BusinessOperationHour.create!(business_id: business1.id, operation_hour_id: sunOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business1.id, operation_hour_id: sunClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business1.id, operation_hour_id: monOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business1.id, operation_hour_id: monClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business2.id, operation_hour_id: wedOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business2.id, operation_hour_id: wedClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business2.id, operation_hour_id: thursOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business2.id, operation_hour_id: thursClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business2.id, operation_hour_id: friOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business2.id, operation_hour_id: friClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business3.id, operation_hour_id: tuesOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business3.id, operation_hour_id: tuesClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business3.id, operation_hour_id: wedOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business3.id, operation_hour_id: wedClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business4.id, operation_hour_id: sunOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business4.id, operation_hour_id: sunClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business4.id, operation_hour_id: tuesOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business4.id, operation_hour_id: tuesClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business4.id, operation_hour_id: thursOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business4.id, operation_hour_id: thursClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business5.id, operation_hour_id: tuesOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business5.id, operation_hour_id: tuesClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business5.id, operation_hour_id: friOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business5.id, operation_hour_id: friClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business5.id, operation_hour_id: satOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business5.id, operation_hour_id: satClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business6.id, operation_hour_id: monOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business6.id, operation_hour_id: monClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business6.id, operation_hour_id: tuesOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business6.id, operation_hour_id: tuesClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business6.id, operation_hour_id: wedOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business6.id, operation_hour_id: wedClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business7.id, operation_hour_id: thursOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business7.id, operation_hour_id: thursClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business7.id, operation_hour_id: friOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business7.id, operation_hour_id: friClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business7.id, operation_hour_id: satOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business7.id, operation_hour_id: satClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business8.id, operation_hour_id: sunOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business8.id, operation_hour_id: sunClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business8.id, operation_hour_id: monOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business8.id, operation_hour_id: monClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business8.id, operation_hour_id: tuesOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business8.id, operation_hour_id: tuesClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business9.id, operation_hour_id: wedOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business9.id, operation_hour_id: wedClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business9.id, operation_hour_id: thursOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business9.id, operation_hour_id: thursClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business9.id, operation_hour_id: friOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business9.id, operation_hour_id: friClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business10.id, operation_hour_id: friOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business10.id, operation_hour_id: friClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business10.id, operation_hour_id: satOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business10.id, operation_hour_id: satClose.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business10.id, operation_hour_id: wedOpen.id)
sbhB1H1 = BusinessOperationHour.create!(business_id: business10.id, operation_hour_id: wedClose.id)

# Seeding images
review1.image.attach(io: File.open("app/assets/images/cauldron.jpg"), filename: "cauldron.jpg" )
review2.image.attach(io: File.open("app/assets/images/cauldron.jpg"), filename: "cauldron.jpg" )
review3.image.attach(io: File.open("app/assets/images/cauldron.jpg"), filename: "cauldron.jpg" )
review4.image.attach(io: File.open("app/assets/images/cauldron.jpg"), filename: "cauldron.jpg" )
